name: Automating Pipeline

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.6.5

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze project source
      #   run: flutter analyze

      - name: Run tests
        run: flutter test
